services:
  backend:
    image: essaidimaryem/ml-pipeline-backend:latest
    container_name: backend
    environment:
      - DOCKER=true
      - EMAIL_PASSWORD=epcu lndl gwiy wole
      - SENDER_EMAIL=maryemessaidi8@gmail.com
      - RECIPIENT_EMAIL=maryem.essaidi@esprit.tn
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./tests:/app/tests
    networks:
      - ml_network
    depends_on:
      - mlflow

  frontend:
    image: essaidimaryem/ml-pipeline-frontend:latest
    container_name: frontend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"
    networks:
      - ml_network
    depends_on:
      - backend

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "/mlruns"]
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    networks:
      - ml_network

  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - ml_network

  kibana:
    image: kibana:8.12.2
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - ml_network

networks:
  ml_network:
    driver: bridge
