services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend-data:/app/data
    depends_on:
      - elasticsearch
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - ml_network

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5001:5001"
    volumes:
      - ./mlruns:/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:///mlruns
    networks:
      - ml_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - ml_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - ml_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - ml_network

networks:
  ml_network:
    driver: bridge

volumes:
  backend-data:
