# Use the prebuilt base image with dependencies
FROM essaidimaryem/ml-project:latest

# Set the working directory (consistent with other services)
WORKDIR /app

# Expose MLflow's default tracking server port
EXPOSE 5000

# Start MLflow server
CMD ["mlflow", "server", "--backend-store-uri", "file:///mlruns", "--host", "0.0.0.0", "--port", "5000"]
